name: client
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <=3.5.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  # 日志打印 https://pub.dev/packages/logger
  logger: ^2.0.1
  # 本地存储 https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.1
  # 事务通知 https://pub.dev/packages/event_bus
  event_bus: ^2.0.0
  # 屏幕适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: 5.9.0
  # 路由 https://pub.flutter-io.cn/packages/fluro
  fluro: ^2.0.5
  # https://pub.dev/packages/intl
  intl: ^0.19.0
  # 网络图片加载 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.3.1
  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^5.3.2
  # 全局状态管理 https://pub.flutter-io.cn/packages/provider
  provider: ^6.0.5
  # 权限申请 https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^10.4.3
  # 间距组件 https://pub-web.flutter-io.cn/packages/gap/changelog
  gap: ^3.0.1
  # 加载弹窗 https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 数字精度 https://pub.dev/packages/decimal
  decimal: ^2.2.0
  # 设备信息 https://pub.dev/packages/device_info_plus
  device_info_plus: ^10.1.2
  # 刷新列表 https://pub-web.flutter-io.cn/packages/easy_refresh
  easy_refresh: ^3.4.0
  # 连接状态 https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.1.3
  # 方形输入框 https://pub-web.flutter-io.cn/packages/pin_code_fields
  pin_code_fields: ^8.0.1
  # 阿里云一键登录 https://pub-web.flutter-io.cn/packages/flutter_ali_auth#Android
  ali_auth: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

