// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/iter-x/iter-x/internal/repo/ent/continent"
	"github.com/iter-x/iter-x/internal/repo/ent/pointsofinterest"
	"github.com/iter-x/iter-x/internal/repo/ent/predicate"
)

// ContinentUpdate is the builder for updating Continent entities.
type ContinentUpdate struct {
	config
	hooks    []Hook
	mutation *ContinentMutation
}

// Where appends a list predicates to the ContinentUpdate builder.
func (cu *ContinentUpdate) Where(ps ...predicate.Continent) *ContinentUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ContinentUpdate) SetUpdatedAt(t time.Time) *ContinentUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetName sets the "name" field.
func (cu *ContinentUpdate) SetName(s string) *ContinentUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *ContinentUpdate) SetNillableName(s *string) *ContinentUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetNameEn sets the "name_en" field.
func (cu *ContinentUpdate) SetNameEn(s string) *ContinentUpdate {
	cu.mutation.SetNameEn(s)
	return cu
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (cu *ContinentUpdate) SetNillableNameEn(s *string) *ContinentUpdate {
	if s != nil {
		cu.SetNameEn(*s)
	}
	return cu
}

// SetNameCn sets the "name_cn" field.
func (cu *ContinentUpdate) SetNameCn(s string) *ContinentUpdate {
	cu.mutation.SetNameCn(s)
	return cu
}

// SetNillableNameCn sets the "name_cn" field if the given value is not nil.
func (cu *ContinentUpdate) SetNillableNameCn(s *string) *ContinentUpdate {
	if s != nil {
		cu.SetNameCn(*s)
	}
	return cu
}

// AddPoiIDs adds the "poi" edge to the PointsOfInterest entity by IDs.
func (cu *ContinentUpdate) AddPoiIDs(ids ...uuid.UUID) *ContinentUpdate {
	cu.mutation.AddPoiIDs(ids...)
	return cu
}

// AddPoi adds the "poi" edges to the PointsOfInterest entity.
func (cu *ContinentUpdate) AddPoi(p ...*PointsOfInterest) *ContinentUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cu.AddPoiIDs(ids...)
}

// Mutation returns the ContinentMutation object of the builder.
func (cu *ContinentUpdate) Mutation() *ContinentMutation {
	return cu.mutation
}

// ClearPoi clears all "poi" edges to the PointsOfInterest entity.
func (cu *ContinentUpdate) ClearPoi() *ContinentUpdate {
	cu.mutation.ClearPoi()
	return cu
}

// RemovePoiIDs removes the "poi" edge to PointsOfInterest entities by IDs.
func (cu *ContinentUpdate) RemovePoiIDs(ids ...uuid.UUID) *ContinentUpdate {
	cu.mutation.RemovePoiIDs(ids...)
	return cu
}

// RemovePoi removes "poi" edges to PointsOfInterest entities.
func (cu *ContinentUpdate) RemovePoi(p ...*PointsOfInterest) *ContinentUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cu.RemovePoiIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ContinentUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ContinentUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ContinentUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ContinentUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ContinentUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := continent.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ContinentUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := continent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Continent.name": %w`, err)}
		}
	}
	if v, ok := cu.mutation.NameEn(); ok {
		if err := continent.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Continent.name_en": %w`, err)}
		}
	}
	if v, ok := cu.mutation.NameCn(); ok {
		if err := continent.NameCnValidator(v); err != nil {
			return &ValidationError{Name: "name_cn", err: fmt.Errorf(`ent: validator failed for field "Continent.name_cn": %w`, err)}
		}
	}
	return nil
}

func (cu *ContinentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(continent.Table, continent.Columns, sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(continent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(continent.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.NameEn(); ok {
		_spec.SetField(continent.FieldNameEn, field.TypeString, value)
	}
	if value, ok := cu.mutation.NameCn(); ok {
		_spec.SetField(continent.FieldNameCn, field.TypeString, value)
	}
	if cu.mutation.PoiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   continent.PoiTable,
			Columns: []string{continent.PoiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointsofinterest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedPoiIDs(); len(nodes) > 0 && !cu.mutation.PoiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   continent.PoiTable,
			Columns: []string{continent.PoiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointsofinterest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.PoiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   continent.PoiTable,
			Columns: []string{continent.PoiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointsofinterest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{continent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ContinentUpdateOne is the builder for updating a single Continent entity.
type ContinentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContinentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ContinentUpdateOne) SetUpdatedAt(t time.Time) *ContinentUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetName sets the "name" field.
func (cuo *ContinentUpdateOne) SetName(s string) *ContinentUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *ContinentUpdateOne) SetNillableName(s *string) *ContinentUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetNameEn sets the "name_en" field.
func (cuo *ContinentUpdateOne) SetNameEn(s string) *ContinentUpdateOne {
	cuo.mutation.SetNameEn(s)
	return cuo
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (cuo *ContinentUpdateOne) SetNillableNameEn(s *string) *ContinentUpdateOne {
	if s != nil {
		cuo.SetNameEn(*s)
	}
	return cuo
}

// SetNameCn sets the "name_cn" field.
func (cuo *ContinentUpdateOne) SetNameCn(s string) *ContinentUpdateOne {
	cuo.mutation.SetNameCn(s)
	return cuo
}

// SetNillableNameCn sets the "name_cn" field if the given value is not nil.
func (cuo *ContinentUpdateOne) SetNillableNameCn(s *string) *ContinentUpdateOne {
	if s != nil {
		cuo.SetNameCn(*s)
	}
	return cuo
}

// AddPoiIDs adds the "poi" edge to the PointsOfInterest entity by IDs.
func (cuo *ContinentUpdateOne) AddPoiIDs(ids ...uuid.UUID) *ContinentUpdateOne {
	cuo.mutation.AddPoiIDs(ids...)
	return cuo
}

// AddPoi adds the "poi" edges to the PointsOfInterest entity.
func (cuo *ContinentUpdateOne) AddPoi(p ...*PointsOfInterest) *ContinentUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cuo.AddPoiIDs(ids...)
}

// Mutation returns the ContinentMutation object of the builder.
func (cuo *ContinentUpdateOne) Mutation() *ContinentMutation {
	return cuo.mutation
}

// ClearPoi clears all "poi" edges to the PointsOfInterest entity.
func (cuo *ContinentUpdateOne) ClearPoi() *ContinentUpdateOne {
	cuo.mutation.ClearPoi()
	return cuo
}

// RemovePoiIDs removes the "poi" edge to PointsOfInterest entities by IDs.
func (cuo *ContinentUpdateOne) RemovePoiIDs(ids ...uuid.UUID) *ContinentUpdateOne {
	cuo.mutation.RemovePoiIDs(ids...)
	return cuo
}

// RemovePoi removes "poi" edges to PointsOfInterest entities.
func (cuo *ContinentUpdateOne) RemovePoi(p ...*PointsOfInterest) *ContinentUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cuo.RemovePoiIDs(ids...)
}

// Where appends a list predicates to the ContinentUpdate builder.
func (cuo *ContinentUpdateOne) Where(ps ...predicate.Continent) *ContinentUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ContinentUpdateOne) Select(field string, fields ...string) *ContinentUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Continent entity.
func (cuo *ContinentUpdateOne) Save(ctx context.Context) (*Continent, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ContinentUpdateOne) SaveX(ctx context.Context) *Continent {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ContinentUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ContinentUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ContinentUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := continent.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ContinentUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := continent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Continent.name": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.NameEn(); ok {
		if err := continent.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Continent.name_en": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.NameCn(); ok {
		if err := continent.NameCnValidator(v); err != nil {
			return &ValidationError{Name: "name_cn", err: fmt.Errorf(`ent: validator failed for field "Continent.name_cn": %w`, err)}
		}
	}
	return nil
}

func (cuo *ContinentUpdateOne) sqlSave(ctx context.Context) (_node *Continent, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(continent.Table, continent.Columns, sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Continent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, continent.FieldID)
		for _, f := range fields {
			if !continent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != continent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(continent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(continent.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.NameEn(); ok {
		_spec.SetField(continent.FieldNameEn, field.TypeString, value)
	}
	if value, ok := cuo.mutation.NameCn(); ok {
		_spec.SetField(continent.FieldNameCn, field.TypeString, value)
	}
	if cuo.mutation.PoiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   continent.PoiTable,
			Columns: []string{continent.PoiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointsofinterest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedPoiIDs(); len(nodes) > 0 && !cuo.mutation.PoiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   continent.PoiTable,
			Columns: []string{continent.PoiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointsofinterest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.PoiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   continent.PoiTable,
			Columns: []string{continent.PoiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointsofinterest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Continent{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{continent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
