// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/iter-x/iter-x/internal/repo/ent/continent"
)

// Continent is the model entity for the Continent schema.
type Continent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NameEn holds the value of the "name_en" field.
	NameEn string `json:"name_en,omitempty"`
	// NameCn holds the value of the "name_cn" field.
	NameCn string `json:"name_cn,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContinentQuery when eager-loading is set.
	Edges        ContinentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContinentEdges holds the relations/edges for other nodes in the graph.
type ContinentEdges struct {
	// Poi holds the value of the poi edge.
	Poi []*PointsOfInterest `json:"poi,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PoiOrErr returns the Poi value or an error if the edge
// was not loaded in eager-loading.
func (e ContinentEdges) PoiOrErr() ([]*PointsOfInterest, error) {
	if e.loadedTypes[0] {
		return e.Poi, nil
	}
	return nil, &NotLoadedError{edge: "poi"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Continent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case continent.FieldName, continent.FieldNameEn, continent.FieldNameCn:
			values[i] = new(sql.NullString)
		case continent.FieldCreatedAt, continent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case continent.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Continent fields.
func (c *Continent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case continent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				c.ID = *value
			}
		case continent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Time
			}
		case continent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Time
			}
		case continent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case continent.FieldNameEn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_en", values[i])
			} else if value.Valid {
				c.NameEn = value.String
			}
		case continent.FieldNameCn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_cn", values[i])
			} else if value.Valid {
				c.NameCn = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Continent.
// This includes values selected through modifiers, order, etc.
func (c *Continent) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryPoi queries the "poi" edge of the Continent entity.
func (c *Continent) QueryPoi() *PointsOfInterestQuery {
	return NewContinentClient(c.config).QueryPoi(c)
}

// Update returns a builder for updating this Continent.
// Note that you need to call Continent.Unwrap() before calling this method if this Continent
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Continent) Update() *ContinentUpdateOne {
	return NewContinentClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Continent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Continent) Unwrap() *Continent {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Continent is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Continent) String() string {
	var builder strings.Builder
	builder.WriteString("Continent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(c.Name)
	builder.WriteString(", ")
	builder.WriteString("name_en=")
	builder.WriteString(c.NameEn)
	builder.WriteString(", ")
	builder.WriteString("name_cn=")
	builder.WriteString(c.NameCn)
	builder.WriteByte(')')
	return builder.String()
}

// Continents is a parsable slice of Continent.
type Continents []*Continent
