// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/iter-x/iter-x/internal/repo/ent/dailyitinerary"
	"github.com/iter-x/iter-x/internal/repo/ent/dailytrip"
	"github.com/iter-x/iter-x/internal/repo/ent/pointsofinterest"
	"github.com/iter-x/iter-x/internal/repo/ent/trip"
)

// DailyItinerary is the model entity for the DailyItinerary schema.
type DailyItinerary struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TripID holds the value of the "trip_id" field.
	TripID uuid.UUID `json:"trip_id,omitempty"`
	// DailyTripID holds the value of the "daily_trip_id" field.
	DailyTripID uuid.UUID `json:"daily_trip_id,omitempty"`
	// PoiID holds the value of the "poi_id" field.
	PoiID uuid.UUID `json:"poi_id,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DailyItineraryQuery when eager-loading is set.
	Edges        DailyItineraryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DailyItineraryEdges holds the relations/edges for other nodes in the graph.
type DailyItineraryEdges struct {
	// Trip holds the value of the trip edge.
	Trip *Trip `json:"trip,omitempty"`
	// DailyTrip holds the value of the daily_trip edge.
	DailyTrip *DailyTrip `json:"daily_trip,omitempty"`
	// Poi holds the value of the poi edge.
	Poi *PointsOfInterest `json:"poi,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TripOrErr returns the Trip value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DailyItineraryEdges) TripOrErr() (*Trip, error) {
	if e.Trip != nil {
		return e.Trip, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: trip.Label}
	}
	return nil, &NotLoadedError{edge: "trip"}
}

// DailyTripOrErr returns the DailyTrip value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DailyItineraryEdges) DailyTripOrErr() (*DailyTrip, error) {
	if e.DailyTrip != nil {
		return e.DailyTrip, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: dailytrip.Label}
	}
	return nil, &NotLoadedError{edge: "daily_trip"}
}

// PoiOrErr returns the Poi value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DailyItineraryEdges) PoiOrErr() (*PointsOfInterest, error) {
	if e.Poi != nil {
		return e.Poi, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: pointsofinterest.Label}
	}
	return nil, &NotLoadedError{edge: "poi"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyItinerary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailyitinerary.FieldNotes:
			values[i] = new(sql.NullString)
		case dailyitinerary.FieldCreatedAt, dailyitinerary.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case dailyitinerary.FieldID, dailyitinerary.FieldTripID, dailyitinerary.FieldDailyTripID, dailyitinerary.FieldPoiID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyItinerary fields.
func (di *DailyItinerary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailyitinerary.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				di.ID = *value
			}
		case dailyitinerary.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				di.CreatedAt = value.Time
			}
		case dailyitinerary.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				di.UpdatedAt = value.Time
			}
		case dailyitinerary.FieldTripID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field trip_id", values[i])
			} else if value != nil {
				di.TripID = *value
			}
		case dailyitinerary.FieldDailyTripID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field daily_trip_id", values[i])
			} else if value != nil {
				di.DailyTripID = *value
			}
		case dailyitinerary.FieldPoiID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field poi_id", values[i])
			} else if value != nil {
				di.PoiID = *value
			}
		case dailyitinerary.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				di.Notes = value.String
			}
		default:
			di.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyItinerary.
// This includes values selected through modifiers, order, etc.
func (di *DailyItinerary) Value(name string) (ent.Value, error) {
	return di.selectValues.Get(name)
}

// QueryTrip queries the "trip" edge of the DailyItinerary entity.
func (di *DailyItinerary) QueryTrip() *TripQuery {
	return NewDailyItineraryClient(di.config).QueryTrip(di)
}

// QueryDailyTrip queries the "daily_trip" edge of the DailyItinerary entity.
func (di *DailyItinerary) QueryDailyTrip() *DailyTripQuery {
	return NewDailyItineraryClient(di.config).QueryDailyTrip(di)
}

// QueryPoi queries the "poi" edge of the DailyItinerary entity.
func (di *DailyItinerary) QueryPoi() *PointsOfInterestQuery {
	return NewDailyItineraryClient(di.config).QueryPoi(di)
}

// Update returns a builder for updating this DailyItinerary.
// Note that you need to call DailyItinerary.Unwrap() before calling this method if this DailyItinerary
// was returned from a transaction, and the transaction was committed or rolled back.
func (di *DailyItinerary) Update() *DailyItineraryUpdateOne {
	return NewDailyItineraryClient(di.config).UpdateOne(di)
}

// Unwrap unwraps the DailyItinerary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (di *DailyItinerary) Unwrap() *DailyItinerary {
	_tx, ok := di.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyItinerary is not a transactional entity")
	}
	di.config.driver = _tx.drv
	return di
}

// String implements the fmt.Stringer.
func (di *DailyItinerary) String() string {
	var builder strings.Builder
	builder.WriteString("DailyItinerary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", di.ID))
	builder.WriteString("created_at=")
	builder.WriteString(di.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(di.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("trip_id=")
	builder.WriteString(fmt.Sprintf("%v", di.TripID))
	builder.WriteString(", ")
	builder.WriteString("daily_trip_id=")
	builder.WriteString(fmt.Sprintf("%v", di.DailyTripID))
	builder.WriteString(", ")
	builder.WriteString("poi_id=")
	builder.WriteString(fmt.Sprintf("%v", di.PoiID))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(di.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// DailyItineraries is a parsable slice of DailyItinerary.
type DailyItineraries []*DailyItinerary
