// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/iter-x/iter-x/internal/repo/ent/dailyitinerary"
	"github.com/iter-x/iter-x/internal/repo/ent/dailytrip"
	"github.com/iter-x/iter-x/internal/repo/ent/pointsofinterest"
	"github.com/iter-x/iter-x/internal/repo/ent/predicate"
	"github.com/iter-x/iter-x/internal/repo/ent/trip"
)

// DailyItineraryQuery is the builder for querying DailyItinerary entities.
type DailyItineraryQuery struct {
	config
	ctx           *QueryContext
	order         []dailyitinerary.OrderOption
	inters        []Interceptor
	predicates    []predicate.DailyItinerary
	withTrip      *TripQuery
	withDailyTrip *DailyTripQuery
	withPoi       *PointsOfInterestQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DailyItineraryQuery builder.
func (diq *DailyItineraryQuery) Where(ps ...predicate.DailyItinerary) *DailyItineraryQuery {
	diq.predicates = append(diq.predicates, ps...)
	return diq
}

// Limit the number of records to be returned by this query.
func (diq *DailyItineraryQuery) Limit(limit int) *DailyItineraryQuery {
	diq.ctx.Limit = &limit
	return diq
}

// Offset to start from.
func (diq *DailyItineraryQuery) Offset(offset int) *DailyItineraryQuery {
	diq.ctx.Offset = &offset
	return diq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (diq *DailyItineraryQuery) Unique(unique bool) *DailyItineraryQuery {
	diq.ctx.Unique = &unique
	return diq
}

// Order specifies how the records should be ordered.
func (diq *DailyItineraryQuery) Order(o ...dailyitinerary.OrderOption) *DailyItineraryQuery {
	diq.order = append(diq.order, o...)
	return diq
}

// QueryTrip chains the current query on the "trip" edge.
func (diq *DailyItineraryQuery) QueryTrip() *TripQuery {
	query := (&TripClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dailyitinerary.Table, dailyitinerary.FieldID, selector),
			sqlgraph.To(trip.Table, trip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dailyitinerary.TripTable, dailyitinerary.TripColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDailyTrip chains the current query on the "daily_trip" edge.
func (diq *DailyItineraryQuery) QueryDailyTrip() *DailyTripQuery {
	query := (&DailyTripClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dailyitinerary.Table, dailyitinerary.FieldID, selector),
			sqlgraph.To(dailytrip.Table, dailytrip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dailyitinerary.DailyTripTable, dailyitinerary.DailyTripColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPoi chains the current query on the "poi" edge.
func (diq *DailyItineraryQuery) QueryPoi() *PointsOfInterestQuery {
	query := (&PointsOfInterestClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dailyitinerary.Table, dailyitinerary.FieldID, selector),
			sqlgraph.To(pointsofinterest.Table, pointsofinterest.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dailyitinerary.PoiTable, dailyitinerary.PoiColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DailyItinerary entity from the query.
// Returns a *NotFoundError when no DailyItinerary was found.
func (diq *DailyItineraryQuery) First(ctx context.Context) (*DailyItinerary, error) {
	nodes, err := diq.Limit(1).All(setContextOp(ctx, diq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dailyitinerary.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (diq *DailyItineraryQuery) FirstX(ctx context.Context) *DailyItinerary {
	node, err := diq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DailyItinerary ID from the query.
// Returns a *NotFoundError when no DailyItinerary ID was found.
func (diq *DailyItineraryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = diq.Limit(1).IDs(setContextOp(ctx, diq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dailyitinerary.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (diq *DailyItineraryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := diq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DailyItinerary entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DailyItinerary entity is found.
// Returns a *NotFoundError when no DailyItinerary entities are found.
func (diq *DailyItineraryQuery) Only(ctx context.Context) (*DailyItinerary, error) {
	nodes, err := diq.Limit(2).All(setContextOp(ctx, diq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dailyitinerary.Label}
	default:
		return nil, &NotSingularError{dailyitinerary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (diq *DailyItineraryQuery) OnlyX(ctx context.Context) *DailyItinerary {
	node, err := diq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DailyItinerary ID in the query.
// Returns a *NotSingularError when more than one DailyItinerary ID is found.
// Returns a *NotFoundError when no entities are found.
func (diq *DailyItineraryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = diq.Limit(2).IDs(setContextOp(ctx, diq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dailyitinerary.Label}
	default:
		err = &NotSingularError{dailyitinerary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (diq *DailyItineraryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := diq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DailyItineraries.
func (diq *DailyItineraryQuery) All(ctx context.Context) ([]*DailyItinerary, error) {
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryAll)
	if err := diq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DailyItinerary, *DailyItineraryQuery]()
	return withInterceptors[[]*DailyItinerary](ctx, diq, qr, diq.inters)
}

// AllX is like All, but panics if an error occurs.
func (diq *DailyItineraryQuery) AllX(ctx context.Context) []*DailyItinerary {
	nodes, err := diq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DailyItinerary IDs.
func (diq *DailyItineraryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if diq.ctx.Unique == nil && diq.path != nil {
		diq.Unique(true)
	}
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryIDs)
	if err = diq.Select(dailyitinerary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (diq *DailyItineraryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := diq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (diq *DailyItineraryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryCount)
	if err := diq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, diq, querierCount[*DailyItineraryQuery](), diq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (diq *DailyItineraryQuery) CountX(ctx context.Context) int {
	count, err := diq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (diq *DailyItineraryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryExist)
	switch _, err := diq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (diq *DailyItineraryQuery) ExistX(ctx context.Context) bool {
	exist, err := diq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DailyItineraryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (diq *DailyItineraryQuery) Clone() *DailyItineraryQuery {
	if diq == nil {
		return nil
	}
	return &DailyItineraryQuery{
		config:        diq.config,
		ctx:           diq.ctx.Clone(),
		order:         append([]dailyitinerary.OrderOption{}, diq.order...),
		inters:        append([]Interceptor{}, diq.inters...),
		predicates:    append([]predicate.DailyItinerary{}, diq.predicates...),
		withTrip:      diq.withTrip.Clone(),
		withDailyTrip: diq.withDailyTrip.Clone(),
		withPoi:       diq.withPoi.Clone(),
		// clone intermediate query.
		sql:  diq.sql.Clone(),
		path: diq.path,
	}
}

// WithTrip tells the query-builder to eager-load the nodes that are connected to
// the "trip" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DailyItineraryQuery) WithTrip(opts ...func(*TripQuery)) *DailyItineraryQuery {
	query := (&TripClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withTrip = query
	return diq
}

// WithDailyTrip tells the query-builder to eager-load the nodes that are connected to
// the "daily_trip" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DailyItineraryQuery) WithDailyTrip(opts ...func(*DailyTripQuery)) *DailyItineraryQuery {
	query := (&DailyTripClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withDailyTrip = query
	return diq
}

// WithPoi tells the query-builder to eager-load the nodes that are connected to
// the "poi" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DailyItineraryQuery) WithPoi(opts ...func(*PointsOfInterestQuery)) *DailyItineraryQuery {
	query := (&PointsOfInterestClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withPoi = query
	return diq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DailyItinerary.Query().
//		GroupBy(dailyitinerary.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (diq *DailyItineraryQuery) GroupBy(field string, fields ...string) *DailyItineraryGroupBy {
	diq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DailyItineraryGroupBy{build: diq}
	grbuild.flds = &diq.ctx.Fields
	grbuild.label = dailyitinerary.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DailyItinerary.Query().
//		Select(dailyitinerary.FieldCreatedAt).
//		Scan(ctx, &v)
func (diq *DailyItineraryQuery) Select(fields ...string) *DailyItinerarySelect {
	diq.ctx.Fields = append(diq.ctx.Fields, fields...)
	sbuild := &DailyItinerarySelect{DailyItineraryQuery: diq}
	sbuild.label = dailyitinerary.Label
	sbuild.flds, sbuild.scan = &diq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DailyItinerarySelect configured with the given aggregations.
func (diq *DailyItineraryQuery) Aggregate(fns ...AggregateFunc) *DailyItinerarySelect {
	return diq.Select().Aggregate(fns...)
}

func (diq *DailyItineraryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range diq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, diq); err != nil {
				return err
			}
		}
	}
	for _, f := range diq.ctx.Fields {
		if !dailyitinerary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if diq.path != nil {
		prev, err := diq.path(ctx)
		if err != nil {
			return err
		}
		diq.sql = prev
	}
	return nil
}

func (diq *DailyItineraryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DailyItinerary, error) {
	var (
		nodes       = []*DailyItinerary{}
		_spec       = diq.querySpec()
		loadedTypes = [3]bool{
			diq.withTrip != nil,
			diq.withDailyTrip != nil,
			diq.withPoi != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DailyItinerary).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DailyItinerary{config: diq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, diq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := diq.withTrip; query != nil {
		if err := diq.loadTrip(ctx, query, nodes, nil,
			func(n *DailyItinerary, e *Trip) { n.Edges.Trip = e }); err != nil {
			return nil, err
		}
	}
	if query := diq.withDailyTrip; query != nil {
		if err := diq.loadDailyTrip(ctx, query, nodes, nil,
			func(n *DailyItinerary, e *DailyTrip) { n.Edges.DailyTrip = e }); err != nil {
			return nil, err
		}
	}
	if query := diq.withPoi; query != nil {
		if err := diq.loadPoi(ctx, query, nodes, nil,
			func(n *DailyItinerary, e *PointsOfInterest) { n.Edges.Poi = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (diq *DailyItineraryQuery) loadTrip(ctx context.Context, query *TripQuery, nodes []*DailyItinerary, init func(*DailyItinerary), assign func(*DailyItinerary, *Trip)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DailyItinerary)
	for i := range nodes {
		fk := nodes[i].TripID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(trip.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "trip_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (diq *DailyItineraryQuery) loadDailyTrip(ctx context.Context, query *DailyTripQuery, nodes []*DailyItinerary, init func(*DailyItinerary), assign func(*DailyItinerary, *DailyTrip)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DailyItinerary)
	for i := range nodes {
		fk := nodes[i].DailyTripID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(dailytrip.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "daily_trip_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (diq *DailyItineraryQuery) loadPoi(ctx context.Context, query *PointsOfInterestQuery, nodes []*DailyItinerary, init func(*DailyItinerary), assign func(*DailyItinerary, *PointsOfInterest)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DailyItinerary)
	for i := range nodes {
		fk := nodes[i].PoiID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pointsofinterest.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "poi_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (diq *DailyItineraryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := diq.querySpec()
	_spec.Node.Columns = diq.ctx.Fields
	if len(diq.ctx.Fields) > 0 {
		_spec.Unique = diq.ctx.Unique != nil && *diq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, diq.driver, _spec)
}

func (diq *DailyItineraryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dailyitinerary.Table, dailyitinerary.Columns, sqlgraph.NewFieldSpec(dailyitinerary.FieldID, field.TypeUUID))
	_spec.From = diq.sql
	if unique := diq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if diq.path != nil {
		_spec.Unique = true
	}
	if fields := diq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailyitinerary.FieldID)
		for i := range fields {
			if fields[i] != dailyitinerary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if diq.withTrip != nil {
			_spec.Node.AddColumnOnce(dailyitinerary.FieldTripID)
		}
		if diq.withDailyTrip != nil {
			_spec.Node.AddColumnOnce(dailyitinerary.FieldDailyTripID)
		}
		if diq.withPoi != nil {
			_spec.Node.AddColumnOnce(dailyitinerary.FieldPoiID)
		}
	}
	if ps := diq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := diq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := diq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := diq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (diq *DailyItineraryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(diq.driver.Dialect())
	t1 := builder.Table(dailyitinerary.Table)
	columns := diq.ctx.Fields
	if len(columns) == 0 {
		columns = dailyitinerary.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if diq.sql != nil {
		selector = diq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if diq.ctx.Unique != nil && *diq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range diq.predicates {
		p(selector)
	}
	for _, p := range diq.order {
		p(selector)
	}
	if offset := diq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := diq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DailyItineraryGroupBy is the group-by builder for DailyItinerary entities.
type DailyItineraryGroupBy struct {
	selector
	build *DailyItineraryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (digb *DailyItineraryGroupBy) Aggregate(fns ...AggregateFunc) *DailyItineraryGroupBy {
	digb.fns = append(digb.fns, fns...)
	return digb
}

// Scan applies the selector query and scans the result into the given value.
func (digb *DailyItineraryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, digb.build.ctx, ent.OpQueryGroupBy)
	if err := digb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DailyItineraryQuery, *DailyItineraryGroupBy](ctx, digb.build, digb, digb.build.inters, v)
}

func (digb *DailyItineraryGroupBy) sqlScan(ctx context.Context, root *DailyItineraryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(digb.fns))
	for _, fn := range digb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*digb.flds)+len(digb.fns))
		for _, f := range *digb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*digb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := digb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DailyItinerarySelect is the builder for selecting fields of DailyItinerary entities.
type DailyItinerarySelect struct {
	*DailyItineraryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dis *DailyItinerarySelect) Aggregate(fns ...AggregateFunc) *DailyItinerarySelect {
	dis.fns = append(dis.fns, fns...)
	return dis
}

// Scan applies the selector query and scans the result into the given value.
func (dis *DailyItinerarySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dis.ctx, ent.OpQuerySelect)
	if err := dis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DailyItineraryQuery, *DailyItinerarySelect](ctx, dis.DailyItineraryQuery, dis, dis.inters, v)
}

func (dis *DailyItinerarySelect) sqlScan(ctx context.Context, root *DailyItineraryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dis.fns))
	for _, fn := range dis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
