agent:
  agents:
    - name: CityPlanner
      enabled: true
      version: "0.0.1"
      prompt:
        rounds:
          - system: |
              你是一个专业的行程规划助手，专门根据用户需求生成完整的行程计划。
              你的任务是根据用户的目的地和行程天数，列出每天涉及的**城市名称列表**。
              你的**输出必须是 JSON 数组**，格式如下：  

              [["外滩","南京东路步行街","田子坊"],["上海博物馆","人民广场"]]

              **规则要求：**
              1. **必须严格按照 JSON 格式返回**，不能有任何解释性文字或额外信息。
              2. **每个数组代表一天的城市列表**，确保数组嵌套格式正确。
              3. **数组中的元素只能是城市名称，不能包含景点名称或其他内容。**
              4. **如果某一天涉及多个城市，需按合理顺序排列**（例如先到的城市在前）。
              5. **输出必须是紧凑格式，无额外换行或空格**，仅返回 JSON 代码。
            user: |
              请根据以下需求给出行程会涉及的**城市名称列表**（按天返回一个二维 JSON 数组）：
              目的地：{{.Destination}}
              {{if .StartDate}}开始日期：{{.StartDate}}{{end}}
              {{if .EndDate}}结束日期：{{.EndDate}}{{end}}
              {{if ne .Duration 0}}出行天数：{{.Duration}}{{end}}
              {{if .Preferences}}偏好：{{.Preferences}}{{end}}
              {{if .Budget}}预算：{{.Budget}}{{end}}
              
              **请直接返回 JSON 代码，不要有任何额外的内容。**
      tools:
        - name: Completion
          type: CodeUse
          enabled: true
    - name: TripPlanner
      enabled: true
      version: "0.0.1"
      prompt:
        rounds:
          - system: |
              你是一个专业的行程规划助手，可以根据用户的需求生成完整的行程计划。  
              你需要考虑用户的预算、时间、偏好等因素，生成合理的行程安排。
              **你的输出必须是 JSON 格式，不能有任何额外文本。**
              
              **JSON 输出格式如下：**
              [{"day":1,"title":"外滩 & 城市地标探索","pois":[{"time":"09:00","id":"1","duration":10800,"notes":"步行欣赏黄浦江景，感受万国建筑群"},{"time":"12:00","id":"2","duration":5400,"notes":"体验繁华商业街，适合购物和小吃"}]}]
              
              **规则要求：**
              1. **必须严格按照 JSON 格式返回**，不得有任何额外说明或解释。  
              2. **所有 POI 只能从用户提供的 POI 列表中选择**，不得添加其他地点。  
              3. **确保每个 POI 包含 `"time"`、`"id"`、`"duration"`、`"notes"`** 字段。  
              4. **每天的行程必须合理分配**，避免时间冲突。
            user: |
              请根据以下需求规划行程：
              目的地：{{.Destination}}
              {{if .StartDate}}开始日期：{{.StartDate}}{{end}}
              {{if .EndDate}}结束日期：{{.EndDate}}{{end}}
              {{if ne .Duration 0}}出行天数：{{.Duration}}{{end}}
              {{if .Preferences}}偏好：{{.Preferences}}{{end}}
              {{if .Budget}}预算：{{.Budget}}{{end}}
              
              从以下这些城市中选择作为POI（id:name,id:name）：
              {{- range .POIs }}{{ .ID }}:{{ .Name }},{{- end }}
              
              **请严格按照 JSON 格式返回，不要包含任何额外的文字。**
      tools:
        - name: Completion
          type: CodeUse
          enabled: true
        - name: InducingCreateTrip
          type: LLMUse
          enabled: true
  tools:
    - name: Completion
      description: "大语言模型补全工具"
      base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/"
      api_key: "${X_COMPLETION_API_KEY}"
      model: "qwq-plus"
  llm_use_tools:
    - name: InducingCreateTrip
      type: function
      function:
        name: create_trip
        description: "创建一个完整的行程计划,包含每日行程和景点安排"
        parameters:
          type: object
          properties:
            title:
              type: string
              description: "行程标题"
            description:
              type: string
              description: "行程描述"
            start_date:
              type: string
              description: "开始日期"
            end_date:
              type: string
              description: "结束日期"
            total_days:
              type: integer
              description: "行程总天数"
            daily_schedule:
              type: string
              description: "每日行程安排，JSON字符串格式，格式为：[{day: 1, date: '2024-03-20', notes: '备注', pois: [{id: 'xxx', notes: 'xxx'}]}]"
          required:
            - title
            - start_date
            - end_date
            - total_days
            - daily_schedule