agent:
  agents:
    - name: "PlanAgent"
      enabled: true
      version: "0.0.1"
      prompt:
        system_prompt: |
          你是一个专业的行程规划助手，可以根据用户的需求生成完整的行程计划。
          你需要考虑用户的预算、时间、偏好等因素，生成合理的行程安排。
          你的输出应该是一个 JSON 格式的行程计划，如：{"daily_plans":[{"day":1,"title":"Cultural Tour","activities":[{"time":"09:00","name":"Versailles","duration":10800,"notes":"Visit palace & gardens"},{"time":"13:00","name":"Lunch at Le Procope","duration":5400,"notes":"Classic French meal"}]},{"day":2,"title":"Outdoor Adventure","activities":[{"time":"08:00","name":"Balloon Ride","duration":7200,"notes":"Scenic countryside view"}]}]}
        user_prompt: |
          请根据以下需求规划行程：
          目的地：{{.Destination}}
          {{if .StartDate}}开始日期：{{.StartDate}}{{end}}
          {{if .EndDate}}结束日期：{{.EndDate}}{{end}}
          {{if ne .Duration 0}}出行天数：{{.Duration}}{{end}}
          {{if .Preferences}}偏好：{{.Preferences}}{{end}}
          {{if .Budget}}预算：{{.Budget}}{{end}}
        refine_prompt: |
          这里根据activity.name从数据库查询出来的id列表，请把前面的activity对应成具体的id
          {{range .Activities}}
          {{.ID}}: {{.Name}}
          {{end}}
          如果你发现有不存在的点位，id就留空表示
          请只返回每天的activities数组，格式如下：
          {
            "daily_plans": [
              {
                "day": 1,
                "activities": [
                  {"id": "xxx", "name": "xxx", "time": "09:00", "duration": 10800, "notes": "xxx"}
                ]
              }
            ]
          }
      tools:
        - name: Completion
          enabled: true
  tools:
    - name: Completion
      description: "大语言模型补全工具"
      base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/"
      api_key: "${X_COMPLETION_API_KEY}"
      model: "qwen-max-2025-01-25"
