auth:
  jwt:
    secret: "${X_JWT_SECRET}"
    expiration: 3600s
    issuer: "https://github.com/Iter-X/Iter-X"
    refresh_expiration: 720h
  oauth:
    google_client_id: "${X_GOOGLE_CLIENT_ID:PlsChangeMe}"
    google_client_secret: "${X_GOOGLE_CLIENT_SECRET:PlsChangeMe}"
    google_redirect_url: "${X_GOOGLE_REDIRECT_URL:PlsChangeMe}"
    github_client_id: "${X_GITHUB_CLIENT_ID:PlsChange}"
    github_client_secret: "${X_GITHUB_CLIENT_SECRET:PlsChange}"
    github_redirect_url: "${X_GITHUB_REDIRECT_URL:PlsChangeMe}"
    wechat_client_id: "${X_WECHAT_CLIENT_ID:PlsChangeMe}"
    wechat_client_secret: "${X_WECHAT_CLIENT_SECRET:PlsChangeMe}"
    wechat_redirect_url: "${X_WECHAT_REDIRECT_URL:PlsChangeMe}"
  ali_cloud:
    access_key_id: "${X_ACCESS_KEY_ID:PlsChangeMe}"
    access_key_secret: "${X_ACCESS_KEY_SECRET:PlsChangeMe}"
  auth_tokens:
    bundle_id: "${X_BUNDLE_ID:PlsChangeMe}"
    expire: 360s
    package_name: "${X_PACKAGE_NAME:PlsChangeMe}"
    sign_name: "${X_SIGN_NAME:PlsChangeMe}"
    scene_code: "${X_SCENE_CODE:PlsChangeMe}"
    sms_template_code: "${X_SMS_TEMPLATE_CODE:PlsChangeMe}"
    sms_code_expire: 300s
  sms_code:
    expire: 300s
    sign_name: "${X_SMS_SIGN_NAME:PlsChangeMe}"
    template_code: "${X_SMS_TEMPLATE_CODE:PlsChangeMe}"