storage:
  driver: ${X_STORAGE_DRIVER:LOCAL}
  local:
    root: "${X_STORAGE_LOCAL_ROOT:./storage}"
    uploadMethod: "${X_STORAGE_LOCAL_UPLOAD_METHOD:PUT}"
    uploadURL: "${X_STORAGE_LOCAL_UPLOAD_URL:/storage/upload}"
    previewURL: "${X_STORAGE_LOCAL_PREVIEW_URL:/storage/preview}"
    endpoint: "${X_STORAGE_LOCAL_ENDPOINT:http://localhost:8080}"
  ali:
    endpoint: "${X_STORAGE_ALI_ENDPOINT}"
    access_key_id: "${X_STORAGE_ALI_ACCESS_KEY_ID}"
    access_key_secret: "${X_STORAGE_ALI_ACCESS_KEY_SECRET}"
    bucket_name: "${X_STORAGE_ALI_BUCKET}"