-- Create "media" table
CREATE TABLE "media" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "filename" character varying NOT NULL, "file_type" character varying NOT NULL, "storage_type" smallint NOT NULL, "path" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "status" boolean NOT NULL DEFAULT true, "username" character varying NOT NULL, "password" character varying NOT NULL, "email" character varying NOT NULL, "avatar_url" character varying NULL, PRIMARY KEY ("id"));
-- Create "trips" table
CREATE TABLE "trips" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "status" boolean NOT NULL DEFAULT true, "title" character varying NOT NULL, "description" character varying NOT NULL, "start_date" timestamptz NOT NULL, "end_date" timestamptz NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "trips_users_trip" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "daily_trips" table
CREATE TABLE "daily_trips" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "day" bigint NOT NULL, "date" timestamptz NOT NULL, "notes" character varying NULL, "trip_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "daily_trips_trips_daily_trip" FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "daily_trip_items" table
CREATE TABLE "daily_trip_items" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "notes" character varying NULL, "daily_trip_id" uuid NOT NULL, "trip_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "daily_trip_items_daily_trips_daily_trip_item" FOREIGN KEY ("daily_trip_id") REFERENCES "daily_trips" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "daily_trip_items_trips_daily_trip_item" FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "refresh_tokens" table
CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "token" character varying NOT NULL, "expires_at" timestamptz NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "refresh_tokens_users_refresh_token" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
