// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: poi/v1/poi.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointsOfInterestService_SearchPointsOfInterest_FullMethodName = "/poi.v1.PointsOfInterestService/SearchPointsOfInterest"
)

// PointsOfInterestServiceClient is the client API for PointsOfInterestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointsOfInterestServiceClient interface {
	SearchPointsOfInterest(ctx context.Context, in *SearchPointsOfInterestRequest, opts ...grpc.CallOption) (*SearchPointsOfInterestResponse, error)
}

type pointsOfInterestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointsOfInterestServiceClient(cc grpc.ClientConnInterface) PointsOfInterestServiceClient {
	return &pointsOfInterestServiceClient{cc}
}

func (c *pointsOfInterestServiceClient) SearchPointsOfInterest(ctx context.Context, in *SearchPointsOfInterestRequest, opts ...grpc.CallOption) (*SearchPointsOfInterestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPointsOfInterestResponse)
	err := c.cc.Invoke(ctx, PointsOfInterestService_SearchPointsOfInterest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointsOfInterestServiceServer is the server API for PointsOfInterestService service.
// All implementations must embed UnimplementedPointsOfInterestServiceServer
// for forward compatibility.
type PointsOfInterestServiceServer interface {
	SearchPointsOfInterest(context.Context, *SearchPointsOfInterestRequest) (*SearchPointsOfInterestResponse, error)
	mustEmbedUnimplementedPointsOfInterestServiceServer()
}

// UnimplementedPointsOfInterestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointsOfInterestServiceServer struct{}

func (UnimplementedPointsOfInterestServiceServer) SearchPointsOfInterest(context.Context, *SearchPointsOfInterestRequest) (*SearchPointsOfInterestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPointsOfInterest not implemented")
}
func (UnimplementedPointsOfInterestServiceServer) mustEmbedUnimplementedPointsOfInterestServiceServer() {
}
func (UnimplementedPointsOfInterestServiceServer) testEmbeddedByValue() {}

// UnsafePointsOfInterestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointsOfInterestServiceServer will
// result in compilation errors.
type UnsafePointsOfInterestServiceServer interface {
	mustEmbedUnimplementedPointsOfInterestServiceServer()
}

func RegisterPointsOfInterestServiceServer(s grpc.ServiceRegistrar, srv PointsOfInterestServiceServer) {
	// If the following call pancis, it indicates UnimplementedPointsOfInterestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointsOfInterestService_ServiceDesc, srv)
}

func _PointsOfInterestService_SearchPointsOfInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPointsOfInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsOfInterestServiceServer).SearchPointsOfInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointsOfInterestService_SearchPointsOfInterest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsOfInterestServiceServer).SearchPointsOfInterest(ctx, req.(*SearchPointsOfInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PointsOfInterestService_ServiceDesc is the grpc.ServiceDesc for PointsOfInterestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointsOfInterestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poi.v1.PointsOfInterestService",
	HandlerType: (*PointsOfInterestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPointsOfInterest",
			Handler:    _PointsOfInterestService_SearchPointsOfInterest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poi/v1/poi.proto",
}
