name: Docker Image Build and Push

on:
  push:
    tags:
      - 'd*' # 触发条件可以根据你的需求修改

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -f DockerfileBuilder -t ghcr.io/$REPO_OWNER_LOWERCASE/iter-x-builder:latest .
          docker tag ghcr.io/$REPO_OWNER_LOWERCASE/iter-x-builder:latest registry.ap-southeast-1.aliyuncs.com/iter-x/iter-x-builder:latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr
        run: |
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_OWNER_LOWERCASE/iter-x-builder:latest

      - name: Login to Alibaba Cloud Docker Registry
        run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username="${{ secrets.ALIYUN_USERNAME }}" registry.ap-southeast-1.aliyuncs.com --password-stdin

      - name: Push Docker image to Alibaba Cloud Docker Registry
        run: |
          docker push registry.ap-southeast-1.aliyuncs.com/iter-x/iter-x-builder:latest