# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.24.1'

      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler

      - name: Generate code
        run: |
          make init
          make all

      - name: Build
        run: make build

      - name: Test
        run: go test -v ./...
