# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.4'

      # Install protoc
      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler

      - name: Generate code
        run: |
          make init
          make all

      - name: Build
        run: make build

      - name: Test
        run: go test -v ./...

      - name: Build Docker image
        run: |
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_OWNER_LOWERCASE/iter-x:latest .
          docker tag ghcr.io/$REPO_OWNER_LOWERCASE/iter-x:latest registry.ap-southeast-1.aliyuncs.com/iter-x/iter-x:latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr
        run: |
          REPO_OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_OWNER_LOWERCASE/iter-x:latest

      - name: Login to Alibaba Cloud Docker Registry
        run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username="${{ secrets.ALIYUN_USERNAME }}" registry.ap-southeast-1.aliyuncs.com --password-stdin

      - name: Push Docker image to Alibaba Cloud Docker Registry
        run: |
          docker push registry.ap-southeast-1.aliyuncs.com/iter-x/iter-x:latest